blank_issues_enabled: false
contact_links:
  - name: Support Discord
    url: https://crazycloudcraft.de/plugin-support/
    about: Our support Discord, please ask questions and seek support here.
  - name: 
    url: https://github.com/CrazyCloudCraft/worldsystem-updated/wiki
    about: Look at the wiki page for answers for setup instructions command syntax and more.
