# This is a basic workflow to help you get started with Actions

name: Release code changer

on:
  push:
    branches: [ change-to-master-or-main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the Version changer
        run: |
          cd ../ || exit 1
          chmod +x release-code-changer.sh
          ./release-code-changer.sh
